### ISSUE TITLE
fix Bittorrent v2 piece layers field

### ISSUE THREAD

**Issue by Rhilip** [Chocobo1/bencode_online#2]
when represented a Bittorrent v2 torrent in JSON format, the key in `piece layers` field seems not right.
It should display like the value in `pieces root` field.

![image](https://user-images.githubusercontent.com/13842140/93705912-05b82400-fb54-11ea-8387-5532350da56f.png)

**Comment by Chocobo1** [comment]
Upstream issue: https://github.com/themasch/node-bencode/issues/88
