### ISSUE TITLE
How do you represent bencoded strings that contain a `<hex>` tag to avoid ambiguity?

### ISSUE THREAD

**Issue by josecelano** [Chocobo1/bencode_online#3]
Relates to: https://github.com/torrust/bencode2json/issues/7

I implemented a port of the format `<hex>...</hex>` use in this repo to Rust:

https://github.com/torrust/bencode2json/issues/7

And someone told me it's not reversible. I had not realized.

It's just to warn other people using this format. Maybe we can come up with an alternative. I think this is the only repo I've seen using this format.

**Comment by Chocobo1** [comment]
>How do you represent bencoded strings that contain a <hex> tag to avoid ambiguity? 

I don't. I rely on the probability that hitting this edge case is very low for my application. Even if encountered, I can just shrug and say too bad, this isn't supported.

This special representation (`<hex></hex>`) is not so useful for a library author and I don't think it is able to improve it. The best you can do is (probably) try to convert to string and fallback to raw bytes when failed.
